server:
  port: 8083

spring:
  application:
    name: sales-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sales_service
    username: postgres
    password: yers7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: sales-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

# Configuración personalizada de clientes
application:
  clients:
    product:
      url: "http://localhost:8082"